apiVersion: v1
kind: Service
metadata:
  name: prod-deployment-service
spec:
  type: LoadBalancer
  selector:
    app: production-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080